version: '2.2'

services:
  indep:
    build:
      context: .
      args:
        - build_number_ci
    command: npm run watch
    env_file:
      - ./indep.env
    ports:
      - "19101:17101"
    volumes:
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./test:/var/www/test
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
  srl:
    build:
      context: .
      args:
        - build_number_ci
    command: npm run watch
    env_file:
      - srl.env
    ports:
      - "19101:17101"
    volumes:
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./test:/var/www/test
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
